# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [2]:
print(np.version.version)

2.3.5


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [46]:
a=np.random.random(size=(2,3,5))



### 4. Print a.


In [47]:
print(a)


[[[0.4855033  0.45070829 0.50953464 0.0188952  0.29033518]
  [0.3329782  0.92401572 0.02829373 0.39999869 0.41248559]
  [0.70726441 0.81326941 0.33781886 0.65428927 0.89474796]]

 [[0.4899041  0.21072414 0.80297833 0.70098174 0.5628715 ]
  [0.1938616  0.57295595 0.93145648 0.61241754 0.63480064]
  [0.52658147 0.98369629 0.98318514 0.33987601 0.56607512]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [48]:
b=np.ones((5,2,3))


### 6. Print b.


In [49]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [50]:
np.size(a)==np.size(b)


True


### 8. Are you able to add a and b? Why or why not?


In [51]:
"""No, because they don't have the same shape"""

"No, because they don't have the same shape"



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [58]:
c=np.transpose(b,(1,2,0))



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [59]:
d=sum(a,c)
"""It works because they're now the same shape"""


"It works because they're now the same shape"


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [60]:
print(f"tensor a:\n {a}")
print(f"tensor d:\n{d}")
"""\n"""
"""The elements in the sum are element-wise addition of tensors a and c"""



tensor a:
 [[[0.4855033  0.45070829 0.50953464 0.0188952  0.29033518]
  [0.3329782  0.92401572 0.02829373 0.39999869 0.41248559]
  [0.70726441 0.81326941 0.33781886 0.65428927 0.89474796]]

 [[0.4899041  0.21072414 0.80297833 0.70098174 0.5628715 ]
  [0.1938616  0.57295595 0.93145648 0.61241754 0.63480064]
  [0.52658147 0.98369629 0.98318514 0.33987601 0.56607512]]]
tensor d:
[[[1.9754074  1.66143244 2.31251297 1.71987694 1.85320668]
  [1.5268398  2.49697167 1.9597502  2.01241623 2.04728623]
  [2.23384588 2.7969657  2.321004   1.99416528 2.46082308]]

 [[1.9754074  1.66143244 2.31251297 1.71987694 1.85320668]
  [1.5268398  2.49697167 1.9597502  2.01241623 2.04728623]
  [2.23384588 2.7969657  2.321004   1.99416528 2.46082308]]]


'The elements in the sum are element-wise addition of tensors a and c'


### 12. Multiply a and c. Assign the result to e.


In [61]:
e=a*c




### 13. Does e equal to a? Why or why not?


In [63]:
e==a
"""They are the same, because tensor c is the identity tensor"""


'They are the same, because tensor c is the identity tensor'



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [65]:
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [69]:
f=np.empty(d.shape)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [72]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value=d[i][j][k]
            if d_max> value > d_mean:
                f[i][j][k]=75
            elif value == d_mean:
                f[i][j][k]=50
            elif  value==d_min:
                f[i][j][k]=0
            elif value == d_max:
                f[i][j][k]=100
            elif d_min < value < d_mean:
                f[i][j][k] = 25





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [73]:
print(f"Tensor d:\n {d}")
print(f"Tensor f:\n {f}")


Tensor d:
 [[[1.9754074  1.66143244 2.31251297 1.71987694 1.85320668]
  [1.5268398  2.49697167 1.9597502  2.01241623 2.04728623]
  [2.23384588 2.7969657  2.321004   1.99416528 2.46082308]]

 [[1.9754074  1.66143244 2.31251297 1.71987694 1.85320668]
  [1.5268398  2.49697167 1.9597502  2.01241623 2.04728623]
  [2.23384588 2.7969657  2.321004   1.99416528 2.46082308]]]
Tensor f:
 [[[ 25.  25.  75.  25.  25.]
  [  0.  75.  25.  25.  25.]
  [ 75. 100.  75.  25.  75.]]

 [[ 25.  25.  75.  25.  25.]
  [  0.  75.  25.  25.  25.]
  [ 75. 100.  75.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [78]:
bonus=[]

for layer in d:
    bonus_layer=[]
    for row in layer:
        bonus_row=[]
        for value in row:
            if d_max> value > d_mean:
                bonus_row.append("D")
            elif value == d_mean:
                bonus_row.append("C")
            elif  value==d_min:
                bonus_row.append("A")
            elif value == d_max:
                bonus_row.append("E")
            elif d_min < value < d_mean:
                bonus_row.append("B")
        bonus_layer.append(bonus_row)
    bonus.append(bonus_layer)